### PR TITLE
Various improvements to #lang lazy, including a lazy port of racket/list

### PR DESCRIPTION
**Pull request by lexi-lambda**
This pull request adds a variety of improvements to `lazy`.
- Support for calling functions with keywords arguments has been added. This was just a minor macro oversight in `!*app`.
- Removed the self-evaluating behavior of `()`. Racket and Scheme do not support it, so changed that for consistency.
- Added `findf` to the core, which was missing.
- Ported all of `racket/list` to lazy code, now located in `lazy/list`. Along with this change, a new language has been added, `lazy/base`, and `lazy` includes all the bindings from `lazy/base` and `lazy/list`.

This does introduce a potentially _breaking_ change to `lazy`, the removal of self-evaluating `()`. I'm mostly betting on the fact that use of `lazy` is small enough that such a relatively insignificant change should not break any existing code.

### CODE REVIEW

**Comment by samth** [comment]
@stchang would be the best person to review here, and maybe @elibarzilay

**Comment by lexi-lambda** [comment]
Okay, so this originally replaced `lazy`'s `take` implementation with the one from `racket/list`, which has the parameter order reversed. It was brought to my attention by @samth and @elibarzilay that this would break existing code. I have modified `lazy` to export the old version of `take` to maintain backwards compatibility.

Currently, `lazy/list` still exports an updated version of `take`. This means that explicitly requiring `lazy/list` when using `#lang lazy` will override the old, Haskell-influenced implementation with one consistent with Racket. However, this behavior could probably be rather confusing, I'm just not sure what a better solution would be.

**Comment by stchang** [comment]
It would be nice to have more tests (maybe just move the comment block from `lazy.rkt` into the `tests` folder) but otherwise is a nice refactoring. Thanks for adding the extra functions.

**Comment by lexi-lambda** [comment]
@stchang Thanks for merging, but I have to ask—how did you even find this PR from 2015? :)

**Pull request merged**
